name: Build, Push Docker image and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: gonzagomezp1/frontend:latest

    - name: Logout from Docker Hub
      run: docker logout

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Debug Secret Key
      run: |
        echo "{
          \"type\": \"${{ secrets.GCP_TYPE }}\",
          \"project_id\": \"${{ secrets.GCP_PROJECT_ID }}\",
          \"private_key_id\": \"${{ secrets.GCP_PRIVATE_KEY_ID }}\",
          \"private_key\": \"${{ secrets.GCP_PRIVATE_KEY }}\",
          \"client_email\": \"${{ secrets.GCP_CLIENT_EMAIL }}\",
          \"client_id\": \"${{ secrets.GCP_CLIENT_ID }}\"
        }" | head -c 100

    - name: Authenticate Docker to Google Container Registry
      run: |
        echo "{
          \"type\": \"${{ secrets.GCP_TYPE }}\",
          \"project_id\": \"${{ secrets.GCP_PROJECT_ID }}\",
          \"private_key_id\": \"${{ secrets.GCP_PRIVATE_KEY_ID }}\",
          \"private_key\": \"${{ secrets.GCP_PRIVATE_KEY }}\",
          \"client_email\": \"${{ secrets.GCP_CLIENT_EMAIL }}\",
          \"client_id\": \"${{ secrets.GCP_CLIENT_ID }}\"
        }" > /tmp/gcp-key.json
        cat /tmp/gcp-key.json | head -c 100
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud auth configure-docker

    - name: Tag Docker image for GCR
      run: docker tag gonzagomezp1/frontend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

    - name: Push Docker image to GCR
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ingenieria-de-software --zone southamerica-west1

    - name: Deploy to GKE
      run: kubectl apply -f deployment.yaml
