name: Build, Push Docker image and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: gonzagomezp1/frontend:latest

    - name: Logout from Docker Hub
      run: docker logout

    - name: Log in to Google Container Registry
      run: echo "${{ secrets.GCP_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Tag Docker image for GCR
      run: docker tag gonzagomezp1/frontend:latest gcr.io/gonzagomezp1/frontend:latest

    - name: Push Docker image to GCR
      run: docker push gcr.io/gonzagomezp1/frontend:latest

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: frontend-430223

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ingenieria-de-software --zone southamerica-west1

    - name: Deploy to GKE
      run: kubectl apply -f deployment.yaml